config/routes.rb
Rails.application.routes.draw do
  get 'books/top'
  post 'books' => "books#create"
  get 'books' => "books#index"
  get 'books/:id' => "books#show",as: "book"

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => "books#update", as: "update_book"
  delete 'books/:id' => "books#destroy", as: "destroy_book"
  # get '/' => "homes#top"
  root to: "homes#top"
  get 'homes/index'
  get 'homes/show'
  get 'homes/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:alert] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      #     @book = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])  
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:alert] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit "Update Book" %>
  
  <span>
    <%= link_to "Show", book_path(@book.id) %>
  </span>
  <span>
    <%= link_to "Back", "/books" %>
  </span>
  
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
  
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @books.each do |book| %>

    <tr>
      <th><%= book.title %></th>
      <th><%= book.body  %></th>
      <th><%= link_to "Show", book_path(book.id) %></th>
      <th><%= link_to "Edit", edit_book_path(book.id) %></th>
      <th><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></th>
    </tr>
 

  <% end %>
</table>



<h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, local: true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:alert] %>
<h2>Title:</h2>
<p><%= @book.title %></p>

<h2>Body:</h2>
<p><%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", "/books" %>

app/views/books/top.html.erb
<h1>Books#top</h1>
<p>Find me in app/views/books/top.html.erb</p>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/homes/top.html.erb
<h1>ようこそBookersへ!</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to "start", "/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>